/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	Int_comparison_exp:{
		_eq:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"Int",
			array:true,
			arrayRequired:false,
			required:true
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"Int",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	String_comparison_exp:{
		_eq:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_ilike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		_iregex:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_like:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nilike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		_niregex:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nlike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nregex:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nsimilar:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_regex:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_similar:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contribution_votes_aggregate_fields:{
		count:{
			columns:{
				type:"contribution_votes_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			distinct:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	contribution_votes_aggregate_order_by:{
		count:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		max:{
			type:"contribution_votes_max_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		min:{
			type:"contribution_votes_min_order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contribution_votes_arr_rel_insert_input:{
		data:{
			type:"contribution_votes_insert_input",
			array:true,
			arrayRequired:true,
			required:true
		},
		on_conflict:{
			type:"contribution_votes_on_conflict",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contribution_votes_bool_exp:{
		_and:{
			type:"contribution_votes_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		_not:{
			type:"contribution_votes_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"contribution_votes_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		contribution_id:{
			type:"uuid_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		rating:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"users_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"uuid_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contribution_votes_constraint: "enum",
	contribution_votes_insert_input:{
		contribution_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		rating:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"users_obj_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contribution_votes_max_order_by:{
		contribution_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		rating:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contribution_votes_min_order_by:{
		contribution_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		rating:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contribution_votes_on_conflict:{
		constraint:{
			type:"contribution_votes_constraint",
			array:false,
			arrayRequired:false,
			required:true
		},
		update_columns:{
			type:"contribution_votes_update_column",
			array:true,
			arrayRequired:true,
			required:true
		},
		where:{
			type:"contribution_votes_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contribution_votes_order_by:{
		contribution_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		rating:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"users_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contribution_votes_pk_columns_input:{
		contribution_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:true
		},
		user_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	contribution_votes_select_column: "enum",
	contribution_votes_set_input:{
		contribution_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		rating:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contribution_votes_update_column: "enum",
	contributions:{
		contributors:{
			distinct_on:{
				type:"contributors_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contributors_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contributors_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contributors_aggregate:{
			distinct_on:{
				type:"contributors_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contributors_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contributors_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		votes:{
			distinct_on:{
				type:"contribution_votes_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contribution_votes_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contribution_votes_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		votes_aggregate:{
			distinct_on:{
				type:"contribution_votes_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contribution_votes_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contribution_votes_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	contributions_aggregate_fields:{
		count:{
			columns:{
				type:"contributions_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			distinct:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	contributions_bool_exp:{
		_and:{
			type:"contributions_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		_not:{
			type:"contributions_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"contributions_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		artifact:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		author:{
			type:"users_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		category:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		contributors:{
			type:"contributors_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_by:{
			type:"uuid_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		date:{
			type:"date_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		effort:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"uuid_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		impact:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		votes:{
			type:"contribution_votes_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		weight:{
			type:"Int_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributions_constraint: "enum",
	contributions_inc_input:{
		weight:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributions_insert_input:{
		artifact:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		author:{
			type:"users_obj_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		category:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		contributors:{
			type:"contributors_arr_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_by:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		date:{
			type:"date",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		effort:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		impact:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		votes:{
			type:"contribution_votes_arr_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		weight:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributions_obj_rel_insert_input:{
		data:{
			type:"contributions_insert_input",
			array:false,
			arrayRequired:false,
			required:true
		},
		on_conflict:{
			type:"contributions_on_conflict",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributions_on_conflict:{
		constraint:{
			type:"contributions_constraint",
			array:false,
			arrayRequired:false,
			required:true
		},
		update_columns:{
			type:"contributions_update_column",
			array:true,
			arrayRequired:true,
			required:true
		},
		where:{
			type:"contributions_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributions_order_by:{
		artifact:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		author:{
			type:"users_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		category:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		contributors_aggregate:{
			type:"contributors_aggregate_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_by:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		date:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		effort:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		impact:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		votes_aggregate:{
			type:"contribution_votes_aggregate_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		weight:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributions_pk_columns_input:{
		id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	contributions_select_column: "enum",
	contributions_set_input:{
		artifact:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		category:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_by:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		date:{
			type:"date",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		effort:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		impact:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		weight:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributions_update_column: "enum",
	contributors_aggregate_fields:{
		count:{
			columns:{
				type:"contributors_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			distinct:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	contributors_aggregate_order_by:{
		avg:{
			type:"contributors_avg_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		count:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		max:{
			type:"contributors_max_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		min:{
			type:"contributors_min_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		stddev:{
			type:"contributors_stddev_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		stddev_pop:{
			type:"contributors_stddev_pop_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		stddev_samp:{
			type:"contributors_stddev_samp_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		sum:{
			type:"contributors_sum_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		var_pop:{
			type:"contributors_var_pop_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		var_samp:{
			type:"contributors_var_samp_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		variance:{
			type:"contributors_variance_order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_arr_rel_insert_input:{
		data:{
			type:"contributors_insert_input",
			array:true,
			arrayRequired:true,
			required:true
		},
		on_conflict:{
			type:"contributors_on_conflict",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_avg_order_by:{
		contribution_share:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_bool_exp:{
		_and:{
			type:"contributors_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		_not:{
			type:"contributors_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"contributors_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		contribution:{
			type:"contributions_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		contribution_id:{
			type:"uuid_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		contribution_share:{
			type:"numeric_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"users_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"uuid_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_constraint: "enum",
	contributors_inc_input:{
		contribution_share:{
			type:"numeric",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_insert_input:{
		contribution:{
			type:"contributions_obj_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		contribution_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		contribution_share:{
			type:"numeric",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"users_obj_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_max_order_by:{
		contribution_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		contribution_share:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_min_order_by:{
		contribution_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		contribution_share:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_on_conflict:{
		constraint:{
			type:"contributors_constraint",
			array:false,
			arrayRequired:false,
			required:true
		},
		update_columns:{
			type:"contributors_update_column",
			array:true,
			arrayRequired:true,
			required:true
		},
		where:{
			type:"contributors_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_order_by:{
		contribution:{
			type:"contributions_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		contribution_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		contribution_share:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"users_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_pk_columns_input:{
		contribution_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:true
		},
		user_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	contributors_select_column: "enum",
	contributors_set_input:{
		contribution_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		contribution_share:{
			type:"numeric",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_stddev_order_by:{
		contribution_share:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_stddev_pop_order_by:{
		contribution_share:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_stddev_samp_order_by:{
		contribution_share:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_sum_order_by:{
		contribution_share:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_update_column: "enum",
	contributors_var_pop_order_by:{
		contribution_share:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_var_samp_order_by:{
		contribution_share:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	contributors_variance_order_by:{
		contribution_share:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	date: "String",
	date_comparison_exp:{
		_eq:{
			type:"date",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"date",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"date",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"date",
			array:true,
			arrayRequired:false,
			required:true
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"date",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"date",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"date",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"date",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	mutation_root:{
		delete_contribution_votes:{
			where:{
				type:"contribution_votes_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_contribution_votes_by_pk:{
			contribution_id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			},
			user_id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_contributions:{
			where:{
				type:"contributions_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_contributions_by_pk:{
			id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_contributors:{
			where:{
				type:"contributors_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_contributors_by_pk:{
			contribution_id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			},
			user_id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_shop_api_users:{
			where:{
				type:"shop_api_users_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_shop_api_users_by_pk:{
			username:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_shop_product_locks:{
			where:{
				type:"shop_product_locks_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_shop_product_locks_by_pk:{
			access_code:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			},
			lock_id:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_users:{
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_users_by_pk:{
			id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		insert_contribution_votes:{
			objects:{
				type:"contribution_votes_insert_input",
				array:true,
				arrayRequired:true,
				required:true
			},
			on_conflict:{
				type:"contribution_votes_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_contribution_votes_one:{
			object:{
				type:"contribution_votes_insert_input",
				array:false,
				arrayRequired:false,
				required:true
			},
			on_conflict:{
				type:"contribution_votes_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_contributions:{
			objects:{
				type:"contributions_insert_input",
				array:true,
				arrayRequired:true,
				required:true
			},
			on_conflict:{
				type:"contributions_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_contributions_one:{
			object:{
				type:"contributions_insert_input",
				array:false,
				arrayRequired:false,
				required:true
			},
			on_conflict:{
				type:"contributions_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_contributors:{
			objects:{
				type:"contributors_insert_input",
				array:true,
				arrayRequired:true,
				required:true
			},
			on_conflict:{
				type:"contributors_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_contributors_one:{
			object:{
				type:"contributors_insert_input",
				array:false,
				arrayRequired:false,
				required:true
			},
			on_conflict:{
				type:"contributors_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_shop_api_users:{
			objects:{
				type:"shop_api_users_insert_input",
				array:true,
				arrayRequired:true,
				required:true
			},
			on_conflict:{
				type:"shop_api_users_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_shop_api_users_one:{
			object:{
				type:"shop_api_users_insert_input",
				array:false,
				arrayRequired:false,
				required:true
			},
			on_conflict:{
				type:"shop_api_users_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_shop_product_locks:{
			objects:{
				type:"shop_product_locks_insert_input",
				array:true,
				arrayRequired:true,
				required:true
			},
			on_conflict:{
				type:"shop_product_locks_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_shop_product_locks_one:{
			object:{
				type:"shop_product_locks_insert_input",
				array:false,
				arrayRequired:false,
				required:true
			},
			on_conflict:{
				type:"shop_product_locks_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_users:{
			objects:{
				type:"users_insert_input",
				array:true,
				arrayRequired:true,
				required:true
			},
			on_conflict:{
				type:"users_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_users_one:{
			object:{
				type:"users_insert_input",
				array:false,
				arrayRequired:false,
				required:true
			},
			on_conflict:{
				type:"users_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		update_contribution_votes:{
			_set:{
				type:"contribution_votes_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"contribution_votes_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_contribution_votes_by_pk:{
			_set:{
				type:"contribution_votes_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			pk_columns:{
				type:"contribution_votes_pk_columns_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_contributions:{
			_inc:{
				type:"contributions_inc_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			_set:{
				type:"contributions_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"contributions_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_contributions_by_pk:{
			_inc:{
				type:"contributions_inc_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			_set:{
				type:"contributions_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			pk_columns:{
				type:"contributions_pk_columns_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_contributors:{
			_inc:{
				type:"contributors_inc_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			_set:{
				type:"contributors_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"contributors_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_contributors_by_pk:{
			_inc:{
				type:"contributors_inc_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			_set:{
				type:"contributors_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			pk_columns:{
				type:"contributors_pk_columns_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_shop_api_users:{
			_set:{
				type:"shop_api_users_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"shop_api_users_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_shop_api_users_by_pk:{
			_set:{
				type:"shop_api_users_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			pk_columns:{
				type:"shop_api_users_pk_columns_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_shop_product_locks:{
			_set:{
				type:"shop_product_locks_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"shop_product_locks_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_shop_product_locks_by_pk:{
			_set:{
				type:"shop_product_locks_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			pk_columns:{
				type:"shop_product_locks_pk_columns_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_users:{
			_set:{
				type:"users_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_users_by_pk:{
			_set:{
				type:"users_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			pk_columns:{
				type:"users_pk_columns_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	numeric: "String",
	numeric_comparison_exp:{
		_eq:{
			type:"numeric",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"numeric",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"numeric",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"numeric",
			array:true,
			arrayRequired:false,
			required:true
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"numeric",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"numeric",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"numeric",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"numeric",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	order_by: "enum",
	query_root:{
		contribution_votes:{
			distinct_on:{
				type:"contribution_votes_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contribution_votes_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contribution_votes_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contribution_votes_aggregate:{
			distinct_on:{
				type:"contribution_votes_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contribution_votes_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contribution_votes_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contribution_votes_by_pk:{
			contribution_id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			},
			user_id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		contributions:{
			distinct_on:{
				type:"contributions_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contributions_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contributions_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contributions_aggregate:{
			distinct_on:{
				type:"contributions_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contributions_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contributions_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contributions_by_pk:{
			id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		contributors:{
			distinct_on:{
				type:"contributors_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contributors_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contributors_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contributors_aggregate:{
			distinct_on:{
				type:"contributors_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contributors_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contributors_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contributors_by_pk:{
			contribution_id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			},
			user_id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		shop_api_users:{
			distinct_on:{
				type:"shop_api_users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"shop_api_users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"shop_api_users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		shop_api_users_aggregate:{
			distinct_on:{
				type:"shop_api_users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"shop_api_users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"shop_api_users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		shop_api_users_by_pk:{
			username:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		shop_product_locks:{
			distinct_on:{
				type:"shop_product_locks_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"shop_product_locks_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"shop_product_locks_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		shop_product_locks_aggregate:{
			distinct_on:{
				type:"shop_product_locks_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"shop_product_locks_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"shop_product_locks_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		shop_product_locks_by_pk:{
			access_code:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			},
			lock_id:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		users:{
			distinct_on:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		users_aggregate:{
			distinct_on:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		users_by_pk:{
			id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	shop_api_users_aggregate_fields:{
		count:{
			columns:{
				type:"shop_api_users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			distinct:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	shop_api_users_bool_exp:{
		_and:{
			type:"shop_api_users_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		_not:{
			type:"shop_api_users_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"shop_api_users_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		password_hash:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		username:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	shop_api_users_constraint: "enum",
	shop_api_users_insert_input:{
		password_hash:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		username:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	shop_api_users_on_conflict:{
		constraint:{
			type:"shop_api_users_constraint",
			array:false,
			arrayRequired:false,
			required:true
		},
		update_columns:{
			type:"shop_api_users_update_column",
			array:true,
			arrayRequired:true,
			required:true
		},
		where:{
			type:"shop_api_users_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	shop_api_users_order_by:{
		password_hash:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		username:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	shop_api_users_pk_columns_input:{
		username:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	shop_api_users_select_column: "enum",
	shop_api_users_set_input:{
		password_hash:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		username:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	shop_api_users_update_column: "enum",
	shop_product_locks_aggregate_fields:{
		count:{
			columns:{
				type:"shop_product_locks_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			distinct:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	shop_product_locks_bool_exp:{
		_and:{
			type:"shop_product_locks_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		_not:{
			type:"shop_product_locks_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"shop_product_locks_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		access_code:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		customer_eth_address:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		lock_id:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	shop_product_locks_constraint: "enum",
	shop_product_locks_insert_input:{
		access_code:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		customer_eth_address:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		lock_id:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	shop_product_locks_on_conflict:{
		constraint:{
			type:"shop_product_locks_constraint",
			array:false,
			arrayRequired:false,
			required:true
		},
		update_columns:{
			type:"shop_product_locks_update_column",
			array:true,
			arrayRequired:true,
			required:true
		},
		where:{
			type:"shop_product_locks_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	shop_product_locks_order_by:{
		access_code:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		customer_eth_address:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		lock_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	shop_product_locks_pk_columns_input:{
		access_code:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		lock_id:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	shop_product_locks_select_column: "enum",
	shop_product_locks_set_input:{
		access_code:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		customer_eth_address:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		lock_id:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	shop_product_locks_update_column: "enum",
	subscription_root:{
		contribution_votes:{
			distinct_on:{
				type:"contribution_votes_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contribution_votes_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contribution_votes_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contribution_votes_aggregate:{
			distinct_on:{
				type:"contribution_votes_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contribution_votes_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contribution_votes_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contribution_votes_by_pk:{
			contribution_id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			},
			user_id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		contributions:{
			distinct_on:{
				type:"contributions_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contributions_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contributions_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contributions_aggregate:{
			distinct_on:{
				type:"contributions_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contributions_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contributions_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contributions_by_pk:{
			id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		contributors:{
			distinct_on:{
				type:"contributors_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contributors_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contributors_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contributors_aggregate:{
			distinct_on:{
				type:"contributors_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"contributors_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"contributors_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contributors_by_pk:{
			contribution_id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			},
			user_id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		shop_api_users:{
			distinct_on:{
				type:"shop_api_users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"shop_api_users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"shop_api_users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		shop_api_users_aggregate:{
			distinct_on:{
				type:"shop_api_users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"shop_api_users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"shop_api_users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		shop_api_users_by_pk:{
			username:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		shop_product_locks:{
			distinct_on:{
				type:"shop_product_locks_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"shop_product_locks_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"shop_product_locks_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		shop_product_locks_aggregate:{
			distinct_on:{
				type:"shop_product_locks_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"shop_product_locks_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"shop_product_locks_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		shop_product_locks_by_pk:{
			access_code:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			},
			lock_id:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		users:{
			distinct_on:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		users_aggregate:{
			distinct_on:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		users_by_pk:{
			id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	timestamptz: "String",
	timestamptz_comparison_exp:{
		_eq:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"timestamptz",
			array:true,
			arrayRequired:false,
			required:true
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"timestamptz",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	users_aggregate_fields:{
		count:{
			columns:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			distinct:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	users_bool_exp:{
		_and:{
			type:"users_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		_not:{
			type:"users_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"users_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		eth_address:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"uuid_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_constraint: "enum",
	users_insert_input:{
		eth_address:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_obj_rel_insert_input:{
		data:{
			type:"users_insert_input",
			array:false,
			arrayRequired:false,
			required:true
		},
		on_conflict:{
			type:"users_on_conflict",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_on_conflict:{
		constraint:{
			type:"users_constraint",
			array:false,
			arrayRequired:false,
			required:true
		},
		update_columns:{
			type:"users_update_column",
			array:true,
			arrayRequired:true,
			required:true
		},
		where:{
			type:"users_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_order_by:{
		eth_address:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_pk_columns_input:{
		id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	users_select_column: "enum",
	users_set_input:{
		eth_address:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_update_column: "enum",
	uuid: "String",
	uuid_comparison_exp:{
		_eq:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"uuid",
			array:true,
			arrayRequired:false,
			required:true
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"uuid",
			array:true,
			arrayRequired:false,
			required:true
		}
	}
}

export const ReturnTypes: Record<string,any> = {
	cached:{
		ttl:"Int",
		refresh:"Boolean"
	},
	contribution_votes:{
		contribution_id:"uuid",
		created_at:"timestamptz",
		rating:"String",
		user:"users",
		user_id:"uuid"
	},
	contribution_votes_aggregate:{
		aggregate:"contribution_votes_aggregate_fields",
		nodes:"contribution_votes"
	},
	contribution_votes_aggregate_fields:{
		count:"Int",
		max:"contribution_votes_max_fields",
		min:"contribution_votes_min_fields"
	},
	contribution_votes_max_fields:{
		contribution_id:"uuid",
		created_at:"timestamptz",
		rating:"String",
		user_id:"uuid"
	},
	contribution_votes_min_fields:{
		contribution_id:"uuid",
		created_at:"timestamptz",
		rating:"String",
		user_id:"uuid"
	},
	contribution_votes_mutation_response:{
		affected_rows:"Int",
		returning:"contribution_votes"
	},
	contributions:{
		artifact:"String",
		author:"users",
		category:"String",
		contributors:"contributors",
		contributors_aggregate:"contributors_aggregate",
		created_at:"timestamptz",
		created_by:"uuid",
		date:"date",
		description:"String",
		effort:"String",
		id:"uuid",
		impact:"String",
		title:"String",
		votes:"contribution_votes",
		votes_aggregate:"contribution_votes_aggregate",
		weight:"Int"
	},
	contributions_aggregate:{
		aggregate:"contributions_aggregate_fields",
		nodes:"contributions"
	},
	contributions_aggregate_fields:{
		avg:"contributions_avg_fields",
		count:"Int",
		max:"contributions_max_fields",
		min:"contributions_min_fields",
		stddev:"contributions_stddev_fields",
		stddev_pop:"contributions_stddev_pop_fields",
		stddev_samp:"contributions_stddev_samp_fields",
		sum:"contributions_sum_fields",
		var_pop:"contributions_var_pop_fields",
		var_samp:"contributions_var_samp_fields",
		variance:"contributions_variance_fields"
	},
	contributions_avg_fields:{
		weight:"Float"
	},
	contributions_max_fields:{
		artifact:"String",
		category:"String",
		created_at:"timestamptz",
		created_by:"uuid",
		date:"date",
		description:"String",
		effort:"String",
		id:"uuid",
		impact:"String",
		title:"String",
		weight:"Int"
	},
	contributions_min_fields:{
		artifact:"String",
		category:"String",
		created_at:"timestamptz",
		created_by:"uuid",
		date:"date",
		description:"String",
		effort:"String",
		id:"uuid",
		impact:"String",
		title:"String",
		weight:"Int"
	},
	contributions_mutation_response:{
		affected_rows:"Int",
		returning:"contributions"
	},
	contributions_stddev_fields:{
		weight:"Float"
	},
	contributions_stddev_pop_fields:{
		weight:"Float"
	},
	contributions_stddev_samp_fields:{
		weight:"Float"
	},
	contributions_sum_fields:{
		weight:"Int"
	},
	contributions_var_pop_fields:{
		weight:"Float"
	},
	contributions_var_samp_fields:{
		weight:"Float"
	},
	contributions_variance_fields:{
		weight:"Float"
	},
	contributors:{
		contribution:"contributions",
		contribution_id:"uuid",
		contribution_share:"numeric",
		user:"users",
		user_id:"uuid"
	},
	contributors_aggregate:{
		aggregate:"contributors_aggregate_fields",
		nodes:"contributors"
	},
	contributors_aggregate_fields:{
		avg:"contributors_avg_fields",
		count:"Int",
		max:"contributors_max_fields",
		min:"contributors_min_fields",
		stddev:"contributors_stddev_fields",
		stddev_pop:"contributors_stddev_pop_fields",
		stddev_samp:"contributors_stddev_samp_fields",
		sum:"contributors_sum_fields",
		var_pop:"contributors_var_pop_fields",
		var_samp:"contributors_var_samp_fields",
		variance:"contributors_variance_fields"
	},
	contributors_avg_fields:{
		contribution_share:"Float"
	},
	contributors_max_fields:{
		contribution_id:"uuid",
		contribution_share:"numeric",
		user_id:"uuid"
	},
	contributors_min_fields:{
		contribution_id:"uuid",
		contribution_share:"numeric",
		user_id:"uuid"
	},
	contributors_mutation_response:{
		affected_rows:"Int",
		returning:"contributors"
	},
	contributors_stddev_fields:{
		contribution_share:"Float"
	},
	contributors_stddev_pop_fields:{
		contribution_share:"Float"
	},
	contributors_stddev_samp_fields:{
		contribution_share:"Float"
	},
	contributors_sum_fields:{
		contribution_share:"numeric"
	},
	contributors_var_pop_fields:{
		contribution_share:"Float"
	},
	contributors_var_samp_fields:{
		contribution_share:"Float"
	},
	contributors_variance_fields:{
		contribution_share:"Float"
	},
	mutation_root:{
		delete_contribution_votes:"contribution_votes_mutation_response",
		delete_contribution_votes_by_pk:"contribution_votes",
		delete_contributions:"contributions_mutation_response",
		delete_contributions_by_pk:"contributions",
		delete_contributors:"contributors_mutation_response",
		delete_contributors_by_pk:"contributors",
		delete_shop_api_users:"shop_api_users_mutation_response",
		delete_shop_api_users_by_pk:"shop_api_users",
		delete_shop_product_locks:"shop_product_locks_mutation_response",
		delete_shop_product_locks_by_pk:"shop_product_locks",
		delete_users:"users_mutation_response",
		delete_users_by_pk:"users",
		insert_contribution_votes:"contribution_votes_mutation_response",
		insert_contribution_votes_one:"contribution_votes",
		insert_contributions:"contributions_mutation_response",
		insert_contributions_one:"contributions",
		insert_contributors:"contributors_mutation_response",
		insert_contributors_one:"contributors",
		insert_shop_api_users:"shop_api_users_mutation_response",
		insert_shop_api_users_one:"shop_api_users",
		insert_shop_product_locks:"shop_product_locks_mutation_response",
		insert_shop_product_locks_one:"shop_product_locks",
		insert_users:"users_mutation_response",
		insert_users_one:"users",
		update_contribution_votes:"contribution_votes_mutation_response",
		update_contribution_votes_by_pk:"contribution_votes",
		update_contributions:"contributions_mutation_response",
		update_contributions_by_pk:"contributions",
		update_contributors:"contributors_mutation_response",
		update_contributors_by_pk:"contributors",
		update_shop_api_users:"shop_api_users_mutation_response",
		update_shop_api_users_by_pk:"shop_api_users",
		update_shop_product_locks:"shop_product_locks_mutation_response",
		update_shop_product_locks_by_pk:"shop_product_locks",
		update_users:"users_mutation_response",
		update_users_by_pk:"users"
	},
	query_root:{
		contribution_votes:"contribution_votes",
		contribution_votes_aggregate:"contribution_votes_aggregate",
		contribution_votes_by_pk:"contribution_votes",
		contributions:"contributions",
		contributions_aggregate:"contributions_aggregate",
		contributions_by_pk:"contributions",
		contributors:"contributors",
		contributors_aggregate:"contributors_aggregate",
		contributors_by_pk:"contributors",
		shop_api_users:"shop_api_users",
		shop_api_users_aggregate:"shop_api_users_aggregate",
		shop_api_users_by_pk:"shop_api_users",
		shop_product_locks:"shop_product_locks",
		shop_product_locks_aggregate:"shop_product_locks_aggregate",
		shop_product_locks_by_pk:"shop_product_locks",
		users:"users",
		users_aggregate:"users_aggregate",
		users_by_pk:"users"
	},
	shop_api_users:{
		password_hash:"String",
		username:"String"
	},
	shop_api_users_aggregate:{
		aggregate:"shop_api_users_aggregate_fields",
		nodes:"shop_api_users"
	},
	shop_api_users_aggregate_fields:{
		count:"Int",
		max:"shop_api_users_max_fields",
		min:"shop_api_users_min_fields"
	},
	shop_api_users_max_fields:{
		password_hash:"String",
		username:"String"
	},
	shop_api_users_min_fields:{
		password_hash:"String",
		username:"String"
	},
	shop_api_users_mutation_response:{
		affected_rows:"Int",
		returning:"shop_api_users"
	},
	shop_product_locks:{
		access_code:"String",
		created_at:"timestamptz",
		customer_eth_address:"String",
		lock_id:"String"
	},
	shop_product_locks_aggregate:{
		aggregate:"shop_product_locks_aggregate_fields",
		nodes:"shop_product_locks"
	},
	shop_product_locks_aggregate_fields:{
		count:"Int",
		max:"shop_product_locks_max_fields",
		min:"shop_product_locks_min_fields"
	},
	shop_product_locks_max_fields:{
		access_code:"String",
		created_at:"timestamptz",
		customer_eth_address:"String",
		lock_id:"String"
	},
	shop_product_locks_min_fields:{
		access_code:"String",
		created_at:"timestamptz",
		customer_eth_address:"String",
		lock_id:"String"
	},
	shop_product_locks_mutation_response:{
		affected_rows:"Int",
		returning:"shop_product_locks"
	},
	subscription_root:{
		contribution_votes:"contribution_votes",
		contribution_votes_aggregate:"contribution_votes_aggregate",
		contribution_votes_by_pk:"contribution_votes",
		contributions:"contributions",
		contributions_aggregate:"contributions_aggregate",
		contributions_by_pk:"contributions",
		contributors:"contributors",
		contributors_aggregate:"contributors_aggregate",
		contributors_by_pk:"contributors",
		shop_api_users:"shop_api_users",
		shop_api_users_aggregate:"shop_api_users_aggregate",
		shop_api_users_by_pk:"shop_api_users",
		shop_product_locks:"shop_product_locks",
		shop_product_locks_aggregate:"shop_product_locks_aggregate",
		shop_product_locks_by_pk:"shop_product_locks",
		users:"users",
		users_aggregate:"users_aggregate",
		users_by_pk:"users"
	},
	users:{
		eth_address:"String",
		id:"uuid",
		name:"String"
	},
	users_aggregate:{
		aggregate:"users_aggregate_fields",
		nodes:"users"
	},
	users_aggregate_fields:{
		count:"Int",
		max:"users_max_fields",
		min:"users_min_fields"
	},
	users_max_fields:{
		eth_address:"String",
		id:"uuid",
		name:"String"
	},
	users_min_fields:{
		eth_address:"String",
		id:"uuid",
		name:"String"
	},
	users_mutation_response:{
		affected_rows:"Int",
		returning:"users"
	}
}